name: Build and test scripts

on:
  push:

jobs:

  # Read teams custom config located in the root (can be made configurable in the future)
  configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: ./.github/scripts/environment-mapper.sh
        env:
          # All apps share the same version, so they can all be deployed and rolled back together (coupling deployments).
          # To change this edit the deployment configuration file to only deploy the app required if preferred. (OPTIONAL)
          VERSION: 1.0.0
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrixx }}

  performance-test-configuration:
    runs-on: ubuntu-latest
    needs: [ configuration ]
    steps:
      - uses: actions/checkout@v3
      - id: set-performance-test-matrix
        run: ./.github/scripts/performance-test-matrix.sh
        env:
          CURRENT_MATRIX: ${{ toJson(needs.configuration.outputs.matrixx).dev }}
    outputs:
      performance-test-matrix: ${{ steps.set-performance-test-matrix.outputs.performance-test-matrix }}
